BASICS OF NUMPY

In [3]:
import numpy as np

creating array for list

In [5]:
arr_1d= np.array([1,2,3])
print("1 D array is: ",arr_1d)

1 D array is:  [1 2 3]


In [6]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array is: ", arr_2d)

2D array is:  [[1 2 3]
 [4 5 6]]


list vs numpy array

In [7]:
py_list=[1,2,3]
print("python list multiplication: ",py_list*2)

python list multiplication:  [1, 2, 3, 1, 2, 3]


In [8]:
np_array=np.array([1,2,3]) ##element wise multiplication
print("python array multiplication: ",np_array *2)

python array multiplication:  [2 4 6]


In [9]:
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n list operation time: ",time.time()-start)


 list operation time:  0.4252159595489502


In [11]:
start=time.time()
arr=np.arange(1000000)*2
print("/n array operation time: ",time.time()-start)

/n array operation time:  0.018152475357055664


Creating array from Scratch

In [12]:
zeros=np.zeros((3,4))
print("zeros array: \n",zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
ones=np.ones((3,4))
print("ones array: \n",ones)

ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
full=np.full((2,2),7)
print("full array: \n",full)

full array: 
 [[7 7]
 [7 7]]


In [15]:
random=np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.04933794 0.24332861 0.23793557]
 [0.78071641 0.33885428 0.71102313]]


In [17]:
sequence=np.arange(0,10,2)
print("sequence array: \n", sequence)

sequence array: 
 [0 2 4 6 8]


vector ,matrix and tensor

In [18]:
vector=np.array([1,2,3])
print("vector ", vector)

vector  [1 2 3]


In [19]:
matrix=np.array([[1,2,3],[4,5,6]])
print("matrix: ",matrix)

matrix:  [[1 2 3]
 [4 5 6]]


In [21]:
tensor=np.array([[[1,2,3],[4,5,6]],
                 [[1,2,3],[4,5,6]]])
print("tensor is;" ,tensor)

tensor is; [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Array Properties

In [10]:
import numpy as np
ar=np.array([[1,2],[3,4]])
print("shape: ",ar.shape)
print("dimension: ",ar.ndim)
print("size: ",ar.size)
print("Data type: ",ar.dtype)

shape:  (2, 2)
dimension:  2
size:  4
Data type:  int64


array reshaping

In [21]:
arr=np.arange(12)
print("Original array: ",arr)

reshaped =arr.reshape((3,4))
print("reshaped array:", reshaped)

flattend=reshaped.flatten()
print("\n flattend array is:", flattend)

# ravel(returns view instead of copy )
raveled_array=reshaped.ravel()
print("\n reveled array: ",raveled_array)

# transpose
transposed=reshaped.T
print("\n transpose array: ",transposed)


Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattend array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
