numpy array operations

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing ",arr[2:7])
print("with step" ,arr[1:8:2])
print("negative indexing ",arr[-3])

basic slicing  [3 4 5 6 7]
with step [2 4 6 8]
negative indexing  8


In [6]:
array_2d=np.array([[1,2],
                   [3,4],
                   [5,6]])
print("specific element",array_2d[1,1])
print("entire row:",array_2d[1])
print("entire col:",array_2d[:,1])


specific element 4
entire row: [3 4]
entire col: [2 4 6]


Sorting

In [7]:
unsorted=np.array([5,7,2,9,1,3,7,0,3,7,8])
print("sorted arrayy ",np.sort(unsorted))

sorted arrayy  [0 1 2 3 3 5 7 7 7 8 9]


In [10]:
array_2d_unsorted=np.array([[1,5],[8,2],[9,4]])
print("unsorted array:",array_2d_unsorted)
print("sorted 2d by col:",np.sort(array_2d_unsorted,axis=0))
print("sorted 2d by row:",np.sort(array_2d_unsorted,axis=1))

unsorted array: [[1 5]
 [8 2]
 [9 4]]
sorted 2d by col: [[1 2]
 [8 4]
 [9 5]]
sorted 2d by row: [[1 5]
 [2 8]
 [4 9]]


filtering

In [12]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
even_num=num[num%2==0]
print("even numbers:",even_num)

even numbers: [ 2  4  6  8 10]


filter with mask

In [14]:
mask=num>5
print("numbers greater than 5:", num[mask])

numbers greater than 5: [ 6  7  8  9 10]


fancy indexing vs np.where()

In [20]:
indices=[0,2,4,6]
print("Values at indexes is",num[indices])

where_result=np.where(num>5)
print(where_result)    #stores indexs
print("NP where ",num[where_result])

Values at indexes is [1 3 5 7]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


conditional array

In [22]:
conditional_array=np.where(num>5,num*2,num )
print(conditional_array)

[ 1  2  3  4  5 12 14 16 18 20]


Adding and removing data

In [24]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

sum=arr1+arr2
print(sum)

combined=np.concatenate((arr1,arr2))
print(combined)

[ 6  8 10 12]
[1 2 3 4 5 6 7 8]


Array compatibility

In [26]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,9])

print("compatibility shape: ", a1.shape==a2.shape)

compatibility shape:  True


In [29]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


Delete

In [33]:
a=np.array([1,2,3,4,5,6])
deleted=np.delete(a,2)
print("Array after deletion",deleted)

Array after deletion [1 2 4 5 6]
