
Arithmetic operation

In [1]:
import numpy as np
a1=np.array([1,2,3])
a=a1+2
print(a)

[3 4 5]


In [4]:
a2=np.array([1,2,3])
a3=np.array([1,2,3])
varr=a2+a3
varr2=np.add(a2,a3)
print(varr)

[2 4 6]


In [10]:
A=np.array([1,2,3])
B=np.array([1,2,3])
A1=np.add(A,B)
A2=np.subtract(A,B)
A3=np.multiply(A,B)
A4=np.divide(A,B)
A5=np.mod(A,B)
A6=np.reciprocal(A)
print(A1,A2,A3,A4,A5,A6)

[2 4 6] [0 0 0] [1 4 9] [1. 1. 1.] [0 0 0] [1 0 0]


2D Array

In [6]:
a4=np.array([[1,2,3],[4,5,6]])
a5=np.array([[1,2,3],[4,5,6]])
varadd=a4+a5
print(varadd)

[[ 2  4  6]
 [ 8 10 12]]


MACHINE LEARNING

Arithmetic fn

In [12]:
a6=np.array([1,2,3,4,3,2,1,4,5,3])
print("max: ",np.max(a6))
print("min: ",np.min(a6))
print("position of max argument: ",np.argmax(a6))
print("position of min argument: ",np.argmin(a6))
print("sqr root: ",np.sqrt(a6))
print("sin: ",np.sin(a6))
print("cos: ",np.cos(a6))
print("community sum: ",np.cumsum(a6))

max:  5
min:  1
position of max argument:  8
position of min argument:  0
max:  [1.         1.41421356 1.73205081 2.         1.73205081 1.41421356
 1.         2.         2.23606798 1.73205081]
max:  [ 0.84147098  0.90929743  0.14112001 -0.7568025   0.14112001  0.90929743
  0.84147098 -0.7568025  -0.95892427  0.14112001]
max:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362 -0.9899925  -0.41614684
  0.54030231 -0.65364362  0.28366219 -0.9899925 ]
max:  [ 1  3  6 10 13 15 16 20 25 28]


In [15]:
aa=np.array([[1,2,3],[5,4,6]])
print(np.min(aa,axis=0))
print(np.max(aa,axis=1))

[1 2 3]
[3 6]


shape and reshaping 

In [17]:
a7=np.array([[1,2,3],[4,5,6]])
print(a7.shape)

(2, 3)


In [26]:
b1 = np.array([1,2,4],ndmin=4)
print(b1)
print(b1.shape)

[[[[1 2 4]]]]
(1, 1, 1, 3)


Reshape

In [30]:
b2=np.array([1,2,3,4,5,6])
b3=b2.reshape(3,2)
print(b3)
print(b3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [35]:
b4=np.array([1,2,3,4,5,6,7,9,11,4,7,5])
print(b4)
print(b4.ndim)
print()

b5=b4.reshape(2,3,2)
print(b5)
print(b5.ndim)

[ 1  2  3  4  5  6  7  9 11  4  7  5]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  9]
  [11  4]
  [ 7  5]]]
3


In [36]:
b4=np.array([1,2,3,4,5,6,7,9,11,4,7,5])
print(b4)
print(b4.ndim)
print()

b5=b4.reshape(2,3,2)
print(b5)
print(b5.ndim)
print()

one=b5.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  9 11  4  7  5]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  9]
  [11  4]
  [ 7  5]]]
3

[ 1  2  3  4  5  6  7  9 11  4  7  5]
1


Broadcasting

In [42]:
c1=np.array([1,2,3])
print(c1.shape)
print(c1)
c2=np.array([[1],[2],[3]])
print(c2.shape)
print(c2)
print(c1+c2)

(3,)
[1 2 3]
(3, 1)
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [44]:
c3=np.array([[1],[2]])
print(c3.shape)
c4=np.array([[1,2,3],[1,2,3]])
print(c4.shape)
print(c3+c4)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


Indexing

In [46]:
c5=np.array([9,8,7,6])
print(c5[2])
print(c5[-1])

7
6


In [49]:
c6=np.array([[9,8,7],[4,3,5]])
print(c6)
print(c6.ndim)
print(c6[0,1])

[[9 8 7]
 [4 3 5]]
2
8


In [55]:
c6=np.array([[[9,8,7],[1,2,3]],[[4,3,5],[1,2,3]]]) 
print(c6)
print(c6.ndim)
print(c6[0,1,2])

[[[9 8 7]
  [1 2 3]]

 [[4 3 5]
  [1 2 3]]]
3
3


Slicing

In [62]:
c7=np.array([9,8,7,6,4,5,6,7,9])
print(c7)
print(c7[1:3])
print(c7[1:])
print(c7[:4])
print("stop:",c7[::2])

[9 8 7 6 4 5 6 7 9]
[8 7]
[8 7 6 4 5 6 7 9]
[9 8 7 6]
stop: [9 7 4 6 9]


In [65]:
c8=np.array([[9,8,7,6,7],[4,3,5,6,7]])
print(c8)
print("for 2D:",c8[1,1:])

[[9 8 7 6 7]
 [4 3 5 6 7]]
for 2D: [3 5 6 7]
