numpy array

In [1]:
import numpy as np

In [2]:
x=[1,2,3]
y=np.array(x)
y
print(y.ndim)

1


In [6]:
l=[]
for i in range(1,5):
    int1=int(input("enter:"))
    l.append(int1)
print(np.array(l))    

enter: 1
enter: 2
enter: 3
enter: 4


[1 2 3 4]


In [9]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


multidimensional

In [3]:
arn=np.array([1,2,3],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


zeros

In [15]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ones

In [19]:
arr_one=np.ones(4)
print(arr_one)

[1. 1. 1. 1.]


empty array

In [20]:
arr_emp=np.empty(4)
print(arr_emp)

[1. 1. 1. 1.]


range array

In [21]:
arr_rn=np.arange(4)
print(arr_rn)

[0 1 2 3]


array diagonal

In [22]:
arr_dia=np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
arr_dia=np.eye(3,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


specific interval

In [6]:
arr_lin=np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


create numpy array with random values

rand() generate value b/w 0 and 1

In [2]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.28448248 0.30586153 0.297329   0.4911158 ]


In [5]:
var1=np.random.rand(2,5)
print(var1)

[[0.97422268 0.5857155  0.19264467 0.08395243 0.2386757 ]
 [0.40752167 0.82117949 0.806258   0.6815515  0.12839795]]


randn() generate value close to 0 , mayn  return -ve and +ve no.

In [8]:
var2=np.random.randn(5)
print(var2)

[-0.08668317 -0.52851267  2.07446095 -1.51513566  0.36659186]


ranf() generate value in interval [0.0,1.0)

In [11]:
var3=np.random.ranf(4)
print(var3)

[0.98333107 0.88231498 0.44575927 0.84048356]


randinit() generate value b/w given range

randint(starting ,ending ,total point)

In [12]:
var4=np.random.randint(5,20,10)
print(var4)

[19 19 16 16 17  7 17 15 12 15]


data type in numpy array

In [14]:
a1=np.array([1,2,3,4])
print("Data type:",a1.dtype)

Data type: int64


change datatype

In [16]:
a2=np.array([1,2,3,4],dtype=np.int8)
print("Data type:",a2.dtype)

Data type: int8


with shortcut

In [17]:
a3=np.array([1,2,3,4],dtype="f")
print("Data type:",a3.dtype)

Data type: float32


with function

In [25]:
a3=np.array([1,2,3,4])
new=np.float32(a3)
new_one=np.int_(new)

print("Data type:",a3.dtype)
print("Data type:",new.dtype)
print("Data type:",new_one.dtype)

print(a3)
print(new)
print(new_one)

Data type: int64
Data type: float32
Data type: int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


directly convert

In [26]:
a4= np.array([1,2,3,4])
new1=a4.astype(float)
print(a4)
print(new1)

[1 2 3 4]
[1. 2. 3. 4.]
