Iteration

In [1]:
import numpy as np
a1=np.array([1,2,3,4])
print(a1)
for i1 in a1
    print(i1)

[1 2 3 4]
1
2
3
4


In [4]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
for i2 in a2:
    print(i2)
print()
for i3 in a2:
    for i4 in i3:
        print(i4)


[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]

1
2
3
4
5
6


In [6]:
a3=np.array([[[1,2,3],[4,5,6]]])
print(a3)
print(a3.ndim)
for i5 in a3:
    for i6 in i5:
        for i7 in i6:
            print(i7)
        

[[[1 2 3]
  [4 5 6]]]
3
1
2
3
4
5
6


nditer fn for interation 

In [10]:
a4=np.array([[[1,2,3],[4,5,6]]])
for i8 in np.nditer(a4,flags =['buffered'],op_dtypes=["S"]):
    print(i8)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')


with indexing

In [11]:
a5=np.array([[[1,2,3],[4,5,6]]])
for i9,d in np.ndenumerate(a4,):
    print(i9,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6


copy fn

In [18]:
b1=np.array([1,2,3,4])
co1=b1.copy()
b1[1]=50
print("b1 is: ",b1)
print("copy: ",co1)

b1 is:  [ 1 50  3  4]
copy:  [1 2 3 4]


view fn

In [20]:
b2=np.array([9,7,8,5,3])
vi1=b2.view()
b2[2]=55
print("b2: ",b2)
print("view: ",vi1)

b2:  [ 9  7 55  5  3]
view:  [ 9  7 55  5  3]


Joining 

In [23]:
b3=np.array([1,2,3])
b4=np.array([4,5,6])
b5=np.concatenate((b3,b4))
print(b5)

[1 2 3 4 5 6]


In [27]:
b6=np.array([[1,2],[3,4]])
b7=np.array([[4,5],[6,8]])
b8=np.concatenate((b6,b7),axis=1)
print(b8)

[[1 2 4 5]
 [3 4 6 8]]


Stack fn

In [34]:
c1=np.array([1,2,3,4])
c2=np.array([5,6,7,8])

c3=np.stack((c1,c2),axis=0)
c4=np.hstack((c1,c2))
c5=np.vstack((c1,c2))
c6=np.dstack((c1,c2))
print(c3)
print(c4)
print(c5)
print(c6)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


split fn

In [39]:
c7=np.array([1,2,3,4,5,6])
c8=np.array_split(c7,3)
print(c8)
print(type(c8))
print(c8[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[3 4]


In [46]:
c9=np.array([[[1,2],[3,4],[5,6]]])
print(c9)
c10=np.array_split(c9,3)
c11=np.array_split(c9,3,axis=0)
print(c10)
print(c11)

[[[1 2]
  [3 4]
  [5 6]]]
[array([[[1, 2],
        [3, 4],
        [5, 6]]]), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64)]
[array([[[1, 2],
        [3, 4],
        [5, 6]]]), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64)]


for searching 

In [52]:
d1=np.array([1,2,3,4,5,5,3,7,8,9])
d2=np.where(d1==3)
d3=np.where((d1%2)==0)
print(d2)
print(d3)

(array([2, 6]),)
(array([1, 3, 8]),)


Search sorted array

In [64]:
d2=np.array([1,2,3,4,6,7,8,9])
d3=np.searchsorted(d2,5)
print(d3)
d4 = np.searchsorted(d2,[5,6,7],side="right")
print(d4)

4
[4 5 6]


sort array 

In [67]:
d5=np.array([1,2,3,4,5,5,3,7,8,9])
print(np.sort(d5))
d6=np.array(["A","a","Z","b","c"])
print(np.sort(d6))

[1 2 3 3 4 5 5 7 8 9]
['A' 'Z' 'a' 'b' 'c']


In [69]:
d7=np.array([[8,5,3],[7,9,6]])
print(np.sort(d7))

[[3 5 8]
 [6 7 9]]


filter array

In [72]:
d8=np.array(["A","a","Z","b","c"])
f=[True,False,True,False,True]
d9=d8[f]
print(d9)
print(type(d9))

['A' 'Z' 'c']
<class 'numpy.ndarray'>


Numpy Array Function

shuffle()

In [75]:
e1=np.array([1,2,3,4])
np.random.shuffle(e1)
print(e1)

[2 4 3 1]


unique

In [79]:
e2=np.array([1,2,3,4,5,5,3,7,8,9])
e=np.unique(e2)
e3=np.unique(e2,return_index=True,return_counts=True)
print(e)
print(e3)

[1 2 3 4 5 7 8 9]
(array([1, 2, 3, 4, 5, 7, 8, 9]), array([0, 1, 2, 3, 4, 7, 8, 9]), array([1, 1, 2, 1, 2, 1, 1, 1]))


Resize()

In [80]:
e4=np.array([1,2,3,4,5,5,3,7,8,9])
e5=np.resize(e4,(2,5))
print(e5)

[[1 2 3 4 5]
 [5 3 7 8 9]]


Flatten

In [84]:
e6=np.array([[8,5,3],[7,9,6]])
print(e6.flatten())
print("colmn Flatten: ",e6.flatten(order="F"))
print(" row Flatten: ",e6.flatten(order="C"))
print("Flatten: ",e6.flatten(order="A"))
print("Flatten: ",e6.flatten(order="K"))

[8 5 3 7 9 6]
colmn Flatten:  [8 7 5 9 3 6]
 row Flatten:  [8 5 3 7 9 6]
Flatten:  [8 5 3 7 9 6]
Flatten:  [8 5 3 7 9 6]


Insertion

In [89]:
x=np.array([1,2,3,4])
print(x)
x1=np.insert(x,2,20)
print(x1)
x2=np.insert(x,(2,4),40)
print(x2)

[1 2 3 4]
[ 1  2 20  3  4]
[ 1  2 40  3  4 40]


In [95]:
x3=np.array([[8,5,3],[7,9,6]])
x4=np.insert(x3,2,6,axis=0)
x5=np.insert(x3,2,[22,23,35],axis=0)
print(x4)
print(x5)

[[8 5 3]
 [7 9 6]
 [6 6 6]]
[[ 8  5  3]
 [ 7  9  6]
 [22 23 35]]


Append()

In [96]:
x6=np.array([1,2,3,4])
x7=np.append(x6,6.5)
print(x7)

[1.  2.  3.  4.  6.5]


In [97]:
x8=np.array([[8,5,3],[7,9,6]])
x9=np.append(x8,[[45,46,43]],axis=0)
print(x9)

[[ 8  5  3]
 [ 7  9  6]
 [45 46 43]]


Delete

In [98]:
y=np.array([1,2,3])
d=np.delete(y,2)
print(d)


[1 2]


Matrix

In [99]:
y1=np.matrix([[1,2,3],[4,5,6]])
print(y1)
y2=np.array([[1,2,3],[4,5,6]])
print(y2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [102]:
y3=np.matrix([[1,2,3],[4,5,6]])
y4=np.matrix([[1,2,3],[4,5,6]])
print(y3+y4)
print(y3-y4)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]


In [105]:
y5=np.matrix([[1,2],[4,5]])
y6=np.matrix([[1,2],[4,5]])
print(y5*y6)
print(y5.dot(y6))

[[ 9 12]
 [24 33]]
[[ 9 12]
 [24 33]]


Matrix  fn

Transpose()

In [107]:
y7=np.matrix([[1,2],[4,5]])
print(y7)
print(np.transpose(y7))
print(y7.T)

[[1 2]
 [4 5]]
[[1 4]
 [2 5]]
[[1 4]
 [2 5]]


Swapaxes()

In [109]:
y8=np.matrix([[1,2],[4,5]])
print(np.swapaxes(y8,0,1))

[[1 4]
 [2 5]]


Inverse()

In [111]:
y9=np.matrix([[1,2],[4,5]])
print(np.linalg.inv(y9))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


Power -> np.linalg.matrix_power(var,n)
           n=0 -> I
           n>0 ->power (multi)
           n<0 ->inverse*power

In [115]:
y10=np.matrix([[1,2],[4,5]])
print(np.linalg.matrix_power(y10,2))
print(np.linalg.matrix_power(y10,0))
print(np.linalg.matrix_power(y10,-2))

[[ 9 12]
 [24 33]]
[[1 0]
 [0 1]]
[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


Determinate

In [116]:
z=np.matrix([[1,2],[4,5]])
print(np.linalg.det(z))

-2.9999999999999996
